###### ###### ###### ###### ###### ######
# poetry add sdv@^1.8.0 smartnoise-synth@^1.0.0 sdmetrics@^0.13.0 anonymeter@^1.0.0

# poetry add wheel
# poetry run pip install --no-build-isolation "pyyaml==5.4.1"
# key libraries
#   poetry add pyyaml@^5.4.1 sdv@^1.9.0 smartnoise-synth@^0.3.3 sdmetrics@^0.13.0 anonymeter@^1.0.0
#       disjoint_set
# for Loader
#   poetry add requests boto3
# may sunset
#   poetry add toml tqdm
#            
#            
# poetry add --group dev ipykernel

#  • Updating faker (15.3.4 -> 19.13.0)
#  • Downgrading smartnoise-sql (1.0.3 -> 0.2.12)
#  • Downgrading smartnoise-synth (1.0.3 -> 0.3.3)


#    poetry config virtualenvs.in-project true
#       - limit vitural environment not adding random string
#    poetry env use python
#        - make sure your python link to valid python version
#    poetry lock
#        - install requirements in pyproject.toml
# poetry shell
###### ###### ###### ###### ###### ######

[tool.poetry]
name = "petsard"
version = "0.6.0-alpha"
description = "Facilitates data generation algorithm and their evaluation processes"
authors = [
    "alexchen830 <alexchen830@gmail.com>",
    "matheme-justyn <matheme.justyn@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
anonymeter = "^1.0.0"
pyyaml = "^5.4.1"
smartnoise-synth = "^0.3.3"
wheel = "^0.42.0"
sdv = "^1.9.0"
sdmetrics = "^0.13.0"
requests = "^2.31.0"
boto3 = "^1.34.37"
toml = "^0.10.2"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
