
Loader:
  demo:
    filepath: 'test_data.csv'
Preprocessor:
  demo:
    method: 'default'
    scaler:
        event_time: 'scaler_standard'
        create_time:
          method: 'scaler_timeanchor'
          params:
            reference: 'event_time'
            unit: 'D'
        process_time:
          method: 'scaler_timeanchor'
          params:
            reference: 'event_time'
            unit: 'D'
        complete_time:
          method: 'scaler_timeanchor'
          params:
            reference: 'event_time'
            unit: 'D'
Postprocessor:
  demo:
    method: 'default'
Reporter:
  save_data:
    method: 'save_data'
    output: 'test_output'
    source: 'Postprocessor'
