benchmark_region_name: ap-southeast-1 # Asia Pacific (Singapore)
benchmark_bucket_name:
  public: petsard-benchmark
  private: petsard-benchmark-private
file_ext:
  LoaderPandasCsv:
    - csv
  LoaderPandasExcel:
    - xls
    - xlsx
    - xlsm
    - xlsb
    - odf
    - ods
    - odt
