# https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-remote-function/quick_start/environment.yml

name: remote_conda_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pip:
      - sagemaker>=2.156.0,<3