# Configurations
title:            PETsARD - Gitbook
longtitle:        PETsARD - Gitbook
author:           NICS - PETs
email:            matheme.justyn@gmail.com
description: >
  Build PETsARD Gitbook site with Jekyll Gitbook.

version:          1.0
gitbook_version:  3.2.3

url:              'https://improved-carnival-37n8n84.pages.github.io/'
baseurl:          '/PETsARD-Gitbook/'
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: rundocs/jekyll-rtd-theme
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:title:output_ext
# :year-:month-:day-

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-remote-theme
