# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: SBOM-OSV - Anchore Syft SBOM scan

on:
  push:
    branches: ["main", "dev", "feat/sbom-ci"]
  release:
    types:
      - created
      - edited
  workflow_dispatch:

permissions:
  contents: write # for sbom-action artifact uploads
  actions: read # to find workflow artifacts when attaching release assets

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Scan the repo and generate the sbom
        uses: anchore/sbom-action@v0
        id: dirscan
        with:
          artifact-name: dirscan-sbom.spdx.json
          output-file: dirscan-sbom.spdx.json
          format: spdx-json
      - run: |
          echo DIR SCAN SBOM:
          cat dirscan-sbom.spdx.json

        # - name: syft-image-action
        #   uses: anchore/sbom-action@v0
        #   id: imagescan
        #   with:
        #     image: alpine:latest
        #     artifact-name: imagescan-sbom.spdx
        #     output-file: image.sbom
        # - run: |
        #     echo IMAGE SCAN SBOM:
        #     cat image.sbom

        # - uses: anchore/sbom-action/publish-sbom@v0
        #   with:
        #     sbom-artifact-match: imagescan-sbom.spdx

        # - uses: anchore/sbom-action/publish-sbom@v0
        #   with:
        #     sbom-artifact-match: "^dont-match-anything$"
