name: trivy-license-scan
on:
  push:
    branches: ["main", "dev", "feat/sbom-ci"]
  release:
    types:
      - created
      - edited
  workflow_dispatch:

jobs:
  scan:
    name: Scan License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          pyproject-file: "./pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Activate uv env
        run: source .venv/bin/activate

      - name: Run Trivy license scanner in fs mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "repo"
          scan-ref: "."
          format: "table"
          # output: trivy.txt
          exit-code: "1"
          scanners: "license"
          hide-progress: true
          list-all-pkgs: true

      - name: the real scanning
        run: trivy repo . --format table --output trivy.txt --scanners license --license-full

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
