name: trivy-vuln-scan
on:
  push:
    branches: ["main", "dev", "feat/sbom-ci"]
  release:
    types:
      - created
      - edited
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          exit-code: "1"
          ignore-unfixed: false
          vuln-type: "os,library"
          scanners: "vuln,secret,misconfig,license"
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          hide-progress: true
          list-all-pkgs: true
