name: trivy-vuln-scan
on:
  push:
    branches: ["main", "dev", "feat/sbom-ci"]
  release:
    types:
      - created
      - edited
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          pyproject-file: "./pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: .
          format: table
          exit-code: 0
          output: trivy-report.json
          ignore-unfixed: false
          vuln-type: "os,library"
          scanners: vuln
          severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
          hide-progress: true
          list-all-pkgs: true
